spring:
  application:
    name: DataMigrator
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health, info

datasource:
  source:
    type: "postgres"
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "postgres"
  target:
    type: "postgres"
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "postgres"

    #jdbc:oracle:thin:@localhost:15212:SAP